### ISSUE TITLE
[React] Clicking a chat gives an error

### ISSUE THREAD

**Issue by NamanArora** [NamanArora/SecureChat#3]
When you click any item in the "Existing Chats" -> "Chats" list... it gives an error on navigating.

Fix the navigation to "Chatscreen" from "Chats" tab

**Comment by roblangridge** [comment]
I'll pick this up for you

**Comment by roblangridge** [comment]
PR ready for review

**Comment by NamanArora** [comment]
Thank you! Good luck for hacktoberfest!
